### PR TITLE
digium intercom support

### PR DESCRIPTION
**Pull request by tikismoke**
This allow a digium d70 to work as intercom.
It needs also a provisionning update

### CODE REVIEW

**Comment by bloom1** [comment]
Hi tikismoke! Thanks for your PR.

We switched to PJSIP for our SIP stack and I had to change the syntax of the config file. However, with the plugin you modified, I was not able to make it work. Did you test your code? Does it work on 18.03?

Thanks!

**Comment by tikismoke** [comment]
Indeed it's actually working with the last version installed and a d70.

Wazo - Version : Unknown "phoenix-stretch" | Visitez wazo.community pour plus d'informations 

    Logiciel : Asterisk
    Version : 15.2.2

 	Plugin for Digium D4X, D50, D6X and D70 in version 2.2.1.8. 

Do not know why it says unknown version?

Going to check if I made another modification elsewhere....

**Comment by tikismoke** [comment]
Maybe the pjsip header as to been adapt.

It took me the last weekend with test to make it work. And a lot of google.... As I understood the header is the more important associate to digium conf adaptation

**Comment by tikismoke** [comment]
If need I can give you an ssh access to this host to have a look.

Let me know

**Comment by tikismoke** [comment]
the info comes from here:
https://wiki.asterisk.org/wiki/display/DIGIUM/Digium+Phones+Intercom+and+Monitor :
```
[handler-intercom]
exten => addheader,1,Set(PJSIP_HEADER(add,Alert-Info)=<intercom>)
same => n,Return()
```

and here https://wiki.asterisk.org/wiki/display/DIGIUM/Ringing+Types+and+Intercom
```
    Normal Ringing - normal
    One Ring followed by automated Answer - ring-answer
    Immediate Answer, No ringing - answer
    Visual only, No ringing sound - visual
```

**Comment by bloom1** [comment]
Hi Tikismoke,

I was able to make it work by removing the quotes around the header contents in the dialplan.
```
; Digium
same  =     n,Set(PJSIP_HEADER(add,Alert-Info)=answer)
``` 
is all that is necessary.

Thank you!

**Comment by tikismoke** [comment]
It's already checked but it only allow from maintener no?

**Pull request merged**
