### PR TITLE
Use Python 3.9, new workers, and Bullseye dependencies

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Comment by sopelj** [comment]
Missing packages for `xivo-certs`, `xivo-utils` and `asterisk-config`

**Review by fblackburn1 — DISMISSED** [review]

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
Ah forgot that xivo-config depends from `asterisk`...

**Review by fblackburn1 — APPROVED** [review]

**Comment by fblackburn1** [comment]
`asterisk` has been packaged

**Pull request merged**
