### PR TITLE
[WAZO-1760] Add provisioning server URL to DHCP configuration

### PR DESCRIPTION
**Pull request by bloom1**
Depends-On: https://github.com/wazo-platform/xivo-manage-db/pull/222
Depends-On: https://github.com/wazo-platform/xivo-dao/pull/243

### CODE REVIEW

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
recheck

**Comment by bloom1** [comment]
Tests pass locally when installing the modified xivo-dao in a virtualenv. I guess zuul does not do that?

**Review by pc-m — APPROVED** [review]

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
regate

**Pull request merged**
