### PR TITLE
Add events for remote party (destination) description

### PR DESCRIPTION
**Pull request by nissou91**
**Why:**
 We need to add three types of events:
* one within user dialplan containing the destination_user_uuid 
* one within the conference dialplan containing the conference_id
* one within the meetings dialplan containing the meeting_id

### CODE REVIEW

**Comment by nissou91** [comment]
recheck

**Comment by nissou91** [comment]
recheck

**Comment by nissou91** [comment]
recheck

**Comment by nissou91** [comment]
recheck

**Comment by nissou91** [comment]
recheck

**Review by xxbillouxx — COMMENTED** [review]
Seems to be good :)

But why not creating a variable named `WAZO_CONFBRIDGE_NAME` in wazo-agid/wazo_agid/modules/incoming_conference_set_features.py like that:     `agi.set_variable('WAZO_CONFBRIDGE_NAME', conference.name)` ?

After that you can write:
`same  =   n,CELGenUserEvent(WAZO_REMOTE_PARTY,type: conference,id: ${WAZO_CONFBRIDGE_NAME},name: ${WAZO_CONFBRIDGE_NAME})`

**Comment by nissou91** [comment]
> Seems to be good :)
> 
> But why not creating a variable named `WAZO_CONFBRIDGE_NAME` in wazo-agid/wazo_agid/modules/incoming_conference_set_features.py like that: `agi.set_variable('WAZO_CONFBRIDGE_NAME', conference.name)` ?
> 
> After that you can write: `same = n,CELGenUserEvent(WAZO_REMOTE_PARTY,type: conference,id: ${WAZO_CONFBRIDGE_NAME},name: ${WAZO_CONFBRIDGE_NAME})`

Actually, we decided to not use the `conference_name` variable; so I removed it.

**Review by pc-m — APPROVED** [review]

**Pull request merged**
